<?php

/**
 * @file
 * Contains flisol_2020.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function flisol_2020_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the flisol_2020 module.
    case 'help.page.flisol_2020':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demo FLISoL 2020') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function flisol_2020_theme() {
  return [
    'flisol_2020' => [
      'render element' => 'content',
      'file' => 'flisol_2020.page.inc',
      'template' => 'flisol-2020',
      'variables' => [
        'speaker' => [],
      ],
    ],
  ];
}
