flisol_2020.settings:
  type: config_object
  label: 'FLISoL 2020 config'
  mapping:
    speaker:
      type: mapping
      label: 'Speaker information'
      mapping:
        name:
          type: string
          label: 'Name'
        email:
          type: email
          label: 'Email'
        github_url:
          type: string
          label: 'GitHub profile'
        drupal_url:
          type: string
          label: 'Drupal profile'
